# Site settings
title: Pyronear
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/test-jeckyll" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

# Traduction
trad:
  en:
    home: "Home"
  fr:
    home: "Accueil"
  zh:
    home: "首页"
